### ISSUE TITLE
Shr5 System node and all subnodes require localization nodes

### ISSUE THREAD

**Issue by NoxMortem** [UrsZeidler/shr5rcp#174] opened 2015-01-13 21:56 UTC
Currently it is not possible to add localization nodes

**Comment by UrsZeidler** [comment] 2015-01-26 21:34
duplicate of #170

**Comment by UrsZeidler** [comment] 2015-01-27 19:42
Looks a bit odd in the model explorer. So I made a task in #112 
![shr5 idetifiable](https://cloud.githubusercontent.com/assets/6352038/5925563/abb20088-a664-11e4-8a0f-c6a7925e7b6a.png)

**Closed** 2015-01-27 20:41 UTC
Labels: localisation, model
